### ISSUE TITLE
Allgemeines Todo

### ISSUE THREAD

**Issue by Nicrey** [Nicrey/Wildmark#1]
### Allgemeines
 - [ ] Klassenübersicht
 - [x] Zurückbuttons an wichtigen Stellen 
 - [x] Ändern des Zurückbuttons in Schreibaktivität
 - [x] Updaten von Quest und Abenteuern, falls seit letztem Aufruf geupdated
- [x]  Updaten von Quest, falls seit dem letzten Aufruf geupdated
 - [ ] Compendium Arcanum Gedanken machen => Als viertes Menüelement?
- [x] Icon für die App

### Unwichtiges
- [ ] Masterpasswort zum Löschen und Ändern von Quests und Berichten, bzw. Erstellen von Quests
- [ ] Chat? 

### Berichte
- [x] Ändern von Berichten
- [ ] Zwischenspeichern von Berichten
- [x] Passwortgeschützte Berichte
